version: "0.5"

processes:
  build:
    command: pixi run build
    availability:
      restart: "no"

  cameras:
    command: pixi run cameras
    namespace: nodes
    depends_on:
      build:
        condition: process_completed_successfully
    availability:
      restart: on_failure
      max_restarts: 3
