version: "0.5"

processes:
  build:
    command: pixi run build && pixi run bridge-build
    availability:
      restart: "no"

  bridge:
    command: pixi run bridge
    depends_on:
      build:
        condition: process_completed_successfully

  cameras:
    command: pixi run cameras
    depends_on:
      build:
        condition: process_completed_successfully

  inference:
    command: pixi run inference
    depends_on:
      build:
        condition: process_completed_successfully

  dashboard:
    command: pixi run dashboard
    depends_on:
      bridge:
        condition: process_started
