version: "0.5"

processes:
  build:
    command: pixi run build
    availability:
      restart: "no"

  bridge:
    command: pixi run bridge
    namespace: core
    availability:
      restart: "no"

  # dashboard:
  #   command: pixi run dashboard
  #   namespace: ui
  #   depends_on:
  #     bridge:
  #       condition: process_started
  #       wait_for: 2s
  #   availability:
  #     restart: on_failure
  #     max_restarts: 3
