import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { homedir } from "os";
import { join } from "path";

export interface BubbaloopConfig {
  // WebSocket endpoint for TUI to connect to local zenohd (ws://...)
  endpoint?: string;
  // TCP endpoint of remote server for zenohd to connect to (tcp/ip:port)
  serverEndpoint?: string;
}

const CONFIG_DIR = join(homedir(), ".bubbaloop");
const CONFIG_FILE = join(CONFIG_DIR, "config.json");
const ZENOH_CLI_CONFIG = join(CONFIG_DIR, "zenoh.cli.json5");

export function loadConfig(): BubbaloopConfig {
  try {
    if (existsSync(CONFIG_FILE)) {
      const data = readFileSync(CONFIG_FILE, "utf-8");
      return JSON.parse(data);
    }
  } catch {
    // Ignore errors, return default config
  }
  return {};
}

export function saveConfig(config: BubbaloopConfig): void {
  try {
    if (!existsSync(CONFIG_DIR)) {
      mkdirSync(CONFIG_DIR, { recursive: true });
    }
    writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2));

    // Also update zenoh.cli.json5 if serverEndpoint is set
    if (config.serverEndpoint) {
      updateZenohCliConfig(config.serverEndpoint);
    }
  } catch {
    // Ignore save errors
  }
}

// Generate zenoh.cli.json5 for zenohd client mode
export function updateZenohCliConfig(serverEndpoint: string): void {
  const zenohConfig = `{
  // Auto-generated by bubbaloop TUI
  // Server endpoint: ${serverEndpoint}
  mode: "router",
  connect: {
    endpoints: ["${serverEndpoint}"],
  },
  plugins: {
    remote_api: {
      websocket_port: 10000,
    },
  },
}
`;
  try {
    if (!existsSync(CONFIG_DIR)) {
      mkdirSync(CONFIG_DIR, { recursive: true });
    }
    writeFileSync(ZENOH_CLI_CONFIG, zenohConfig);
  } catch {
    // Ignore errors
  }
}

export function getZenohCliConfigPath(): string {
  return ZENOH_CLI_CONFIG;
}

export const DEFAULT_ENDPOINT = "ws://127.0.0.1:10000";
